# Generated by Django 5.1 on 2024-12-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('about', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('fees', models.IntegerField()),
            ],
        ),
    ]
