# Generated by Django 5.1 on 2024-12-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='about',
            field=models.CharField(max_length=1000),
        ),
    ]
