# Generated by Django 5.1 on 2024-12-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_event_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='icon',
            field=models.ImageField(default='../static/graphics/techfest.svg', upload_to='icons/'),
        ),
    ]
